// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/get_config.ts";
import * as $1 from "./routes/api/status.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Config.tsx";
import * as $$1 from "./islands/MouseActionRuntime.tsx";

const manifest = {
  routes: {
    "./routes/api/get_config.ts": $0,
    "./routes/api/status.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Config.tsx": $$0,
    "./islands/MouseActionRuntime.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
